"""Hexagonal parallel-hole collimator lattice.

A solid lead box labelled "collimator" is not a parallel-hole collimator: it
has no holes, so it has no geometric resolution, no septal penetration and no
open area. Anyone opening the generated geometry file would see a box and
correctly conclude that nothing was modelled.

This module generates the actual hole lattice from the three parameters that
define it — hole diameter, septal thickness and hole length — and exports it as
GAMOS text geometry: a lead body with an air hole placed at every lattice site.

Scale note. A full 500 x 380 mm field of view at a 1.7 mm pitch is of the order
of 10^5 holes, which is a large text geometry. ``fov_x_mm`` / ``fov_y_mm`` are
therefore configurable, so a study can model a representative region at full
fidelity instead of a full field of view badly. A G4 replica or parameterised
volume is the scalable route and is noted in docs/model_card.md.
"""

from __future__ import annotations

import numpy as np


def pitch_mm(hole_diameter_mm: float, septal_thickness_mm: float) -> float:
    """Centre-to-centre distance between neighbouring holes."""
    return hole_diameter_mm + septal_thickness_mm


def hexagonal_lattice(fov_x_mm: float, fov_y_mm: float, hole_diameter_mm: float,
                      septal_thickness_mm: float) -> np.ndarray:
    """Hole centres of a hexagonally packed lattice, shape (n_holes, 2).

    Rows are spaced by pitch * sqrt(3)/2 and alternate rows are offset by half
    a pitch, which is what makes the packing hexagonal rather than square. A
    square lattice with the same pitch has a lower open area and a different
    sensitivity, so this is not a cosmetic detail.
    """
    p = pitch_mm(hole_diameter_mm, septal_thickness_mm)
    row_spacing = p * np.sqrt(3.0) / 2.0
    margin = hole_diameter_mm / 2.0

    centres = []
    n_rows = int((fov_y_mm - 2 * margin) // row_spacing) + 1
    for row in range(n_rows):
        y = -fov_y_mm / 2.0 + margin + row * row_spacing
        if y > fov_y_mm / 2.0 - margin:
            break
        offset = (p / 2.0) if row % 2 else 0.0
        x = -fov_x_mm / 2.0 + margin + offset
        while x <= fov_x_mm / 2.0 - margin:
            centres.append((x, y))
            x += p
    return np.asarray(centres, dtype=float)


def open_area_fraction(centres, hole_diameter_mm: float, fov_x_mm: float,
                       fov_y_mm: float) -> float:
    """Fraction of the modelled face that is hole rather than septum."""
    hole_area = np.pi * (hole_diameter_mm / 2.0) ** 2 * len(centres)
    return float(hole_area / (fov_x_mm * fov_y_mm))


def minimum_septal_thickness(centres, hole_diameter_mm: float) -> float:
    """Smallest lead thickness between neighbouring holes, in mm.

    Recomputed from the generated geometry rather than taken from the config:
    it is the check that the lattice actually respects the septa it claims.
    """
    c = np.asarray(centres, dtype=float)
    if len(c) < 2:
        return float("inf")
    from scipy.spatial import cKDTree

    distances, _ = cKDTree(c).query(c, k=2)
    return float(distances[:, 1].min() - hole_diameter_mm)


def to_gamos_geometry(centres, hole_diameter_mm: float, hole_length_mm: float,
                      fov_x_mm: float, fov_y_mm: float,
                      hole_shape: str = "hexagonal") -> str:
    """GAMOS text geometry: a lead body with an air hole at each lattice site."""
    half_l = hole_length_mm / 2.0
    apothem = hole_diameter_mm / 2.0
    lines = [
        "// Generated by gcmc.collimator — do not edit by hand.",
        (f"// {len(centres)} holes, {hole_shape}, "
         f"modelled face {fov_x_mm} x {fov_y_mm} mm"),
        (f":VOLU collimator BOX {fov_x_mm / 2:.4f} {fov_y_mm / 2:.4f} "
         f"{half_l:.4f} G4_Pb"),
    ]
    if hole_shape == "hexagonal":
        lines.append(":VOLU hole POLYHEDRA 0. 360. 6 2 "
                     f"0. {apothem:.4f} {-half_l:.4f} "
                     f"0. {apothem:.4f} {half_l:.4f} G4_AIR")
    else:
        lines.append(f":VOLU hole TUBE 0. {apothem:.4f} {half_l:.4f} G4_AIR")
    for i, (x, y) in enumerate(centres, start=1):
        lines.append(f":PLACE hole {i} collimator {x:.4f} {y:.4f} 0.")
    return "\n".join(lines) + "\n"
